name = "CobbleCult Modpack"
author = "wamulet"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30b2a591bed27b81fb242b01eb401351635171be6b53656109855a7cbbec17d3"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
