name = "CobbleCult Modpack"
author = "wamulet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5bdea2f7cc2f215c8b4ccb9cfa84fa9874c5f3afa7ed94339f6c5bd4e6254ffc"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
