name = "CobbleCult Modpack"
author = "wamulet"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7e23682f177d3e5846dfeea0e3690adf937198718067d0129f266f81c3d0727"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
